# pipelines/cloudbuild.yaml

substitutions:
  _TFVARS_FILE: "dev.tfvars"
  _GCP_REGION: "us-central1"
  _SERVICE_NAME: "file-parser"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Terraform Format
  - name: "hashicorp/terraform:light"
    id: "Terraform Format"
    entrypoint: "sh"
    args: ["-c", "terraform fmt -check && echo 'Terraform format check passed.'"]
    dir: "terraform"

  # 2. Terraform Lint
  - name: "ghcr.io/terraform-linters/tflint"
    id: "Terraform Lint"
    args: ["--format", "json"]
    dir: "terraform"
    waitFor: ["Terraform Format"]

  # 3. Terraform Init
  - name: "hashicorp/terraform:light"
    id: "Terraform Init"
    entrypoint: "sh"
    args: ["-c", "terraform init"]
    dir: "terraform"
    waitFor: ["Terraform Lint"]

  # 4. Terraform Plan
  - name: "hashicorp/terraform:light"
    id: "Terraform Plan"
    entrypoint: "sh"
    args: ["-c", "terraform plan -var-file=${_TFVARS_FILE} -out=tfplan.out"]
    dir: "terraform"
    waitFor: ["Terraform Init"]

  # 5. Manual Approval (for non-dev)
  - name: "gcr.io/cloud-builders/gcloud"
    id: "Manual Approval"
    entrypoint: "bash"
    args:
      - -c
      - |
        if [[ "${_TFVARS_FILE}" != "dev.tfvars" ]]; then
          echo "Manual approval required for ${_TFVARS_FILE}. Approve in the Cloud Build UI."
          exit 1
        else
          echo "Dev environment detected, skipping approval."
        fi
    waitFor: ["Terraform Plan"]

  # 6. Terraform Apply
  - name: "hashicorp/terraform:light"
    id: "Terraform Apply"
    entrypoint: "sh"
    args: ["-c", "terraform apply -auto-approve tfplan.out"]
    dir: "terraform"
    waitFor: ["Manual Approval"]

  # 7. Build Docker Image
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Docker Image"
    args: [
      "build",
      "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA",
      "./tools/file_parser"
    ]
    waitFor: ["Terraform Apply"]

  # 8. Push Docker Image
  - name: "gcr.io/cloud-builders/docker"
    id: "Push Docker Image"
    args: [
      "push",
      "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
    ]
    waitFor: ["Build Docker Image"]

  # 9. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy to Cloud Run"
    entrypoint: "bash"
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE_NAME} \
          --image gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA \
          --region ${_GCP_REGION} \
          --platform managed \
          --allow-unauthenticated
    waitFor: ["Push Docker Image"]


